### PR TITLE
Updated to work with python3

### PR DESCRIPTION
**Pull request by Pektech**
Hello

Made some changes to have this work with python 3. Mainly print statements, use json instead of simplejson and BaseHTTPRequestHandler to import from http.server.  Seems to be working well with bst proxy and bst launch/utter/intend

This is my first time forking someone elses work and creating a pull. Only messed up my own work before now so please let me know if anything handled incorrectly

### CODE REVIEW

**Review by OpenDog — APPROVED** [review]
All look neat to me!

**Comment by Pektech** [comment]
Cool :) thank you

**Comment by jayhill** [comment]
Any chance of seeing this merged to master?
I've been making the same changes locally for a while now before I saw this.

**Review by OpenDog — APPROVED** [review]

**Comment by Pektech** [comment]
Is there something more I was supposed to do?

**Comment by OpenDog** [comment]
No your good. I just don't have the privileges to merge. I emailed Bespoken.

**Pull request merged**
